cmake_minimum_required(VERSION 3.8)
project(edge_sensor_filters)
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ament_cmake REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_components REQUIRED)
find_package(sensor_msgs REQUIRED)
add_library(sensor_covariance_injector_component SHARED src/sensor_covariance_injector.cpp)
target_include_directories(sensor_covariance_injector_component PUBLIC include)
ament_target_dependencies(sensor_covariance_injector_component nav_msgs rclcpp rclcpp_components sensor_msgs)
rclcpp_components_register_node(sensor_covariance_injector_component
  PLUGIN "edge_sensor_filters::SensorCovarianceInjector"
  EXECUTABLE sensor_covariance_injector)
install(TARGETS sensor_covariance_injector_component ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
install(DIRECTORY include/ DESTINATION include)
if(BUILD_TESTING)
  find_package(ament_cmake_gtest REQUIRED)
  ament_add_gtest(test_covariance test/test_covariance.cpp)
  target_include_directories(test_covariance PRIVATE include)
  ament_target_dependencies(test_covariance nav_msgs sensor_msgs)
  find_package(ament_lint_auto REQUIRED)
  set(ament_cmake_copyright_FOUND TRUE)
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()
ament_package()
